const archiver = require('archiver');

/**
 * Generate README.txt with assembly instructions, laser settings, and stats.
 */
function generateReadme({ cityName, widthMm, heightMm, kerf, stats }) {
  const date = new Date().toISOString().slice(0, 10);

  return `================================================================================
  LaserMap Studio - ${cityName}
  Generated: ${date}
================================================================================

PROJECT OVERVIEW
----------------
City: ${cityName}
Output Size: ${widthMm}mm x ${heightMm}mm
Kerf Compensation: ${kerf}mm
Major Roads: ${stats.majorRoads} segments
Minor Roads: ${stats.minorRoads} segments
Water Features: ${stats.waterFeatures}

FILES INCLUDED
--------------
Layer1_MajorRoads.svg   - Top layer: major road cut polygons + water cutouts
Layer2_MinorRoads.svg   - Middle layer: minor road engrave paths + water cutouts + text
Layer3_Base.svg         - Bottom layer: land silhouette + water holes

MATERIAL RECOMMENDATIONS
-------------------------
- 3mm birch plywood or acrylic for each layer
- Total thickness when stacked: ~9mm (3 layers x 3mm)
- Alternative: 1/8" (3.175mm) material

LASER SETTINGS (adjust for your machine)
-----------------------------------------
CUT paths (stroke="#000000", stroke-width="0.5"):
  - Power: 80-100%
  - Speed: 10-20 mm/s (for 3mm plywood)
  - Passes: 1-2

ENGRAVE paths (stroke="#444444", stroke-width="0.3"):
  - Power: 20-40%
  - Speed: 100-200 mm/s
  - Passes: 1

ASSEMBLY INSTRUCTIONS
---------------------
1. Cut all three layers on your laser cutter
   - Layer 3 (Base): Cut the land silhouette outline and water features
   - Layer 2 (Minor Roads): Cut water features, engrave minor roads and text
   - Layer 1 (Major Roads): Cut major road polygons and water features

2. Align layers using the registration marks (small circles at corners)
   - Each layer has identical registration marks at 8mm from each corner
   - Use pins or dowels through the registration points for alignment

3. Stack layers in order (bottom to top):
   - Layer 3 (Base) - provides the land shape foundation
   - Layer 2 (Minor Roads) - adds street detail and city name
   - Layer 1 (Major Roads) - raised highway network on top

4. Glue layers together
   - Use wood glue for plywood, acrylic cement for acrylic
   - Apply thin, even coat to avoid squeeze-out
   - Clamp gently while drying (30-60 minutes)

5. Optional finishing
   - Sand edges lightly if needed
   - Apply clear coat or oil finish for plywood
   - Frame or mount as desired

REGISTRATION MARKS
------------------
- 4 circles at corners, 3mm diameter, inset 8mm from edges
- Use these to align all three layers precisely
- Drill or cut these marks on each layer for pin alignment

NOTES
-----
- Water features are IDENTICAL across all three layers for alignment
- All paths use no fill; cutting follows stroke paths only
- SVG units are in pixels at 96 DPI (1mm = 3.7795px)
- For best results, do a test cut on scrap material first

================================================================================
  Generated by LaserMap Studio | https://lasermapstudio.com
================================================================================
`;
}

/**
 * Stream a ZIP archive containing SVG layers and README to the response.
 * @param {Stream} outputStream - Express response stream
 * @param {Object} options - { svgLayers: { layer1, layer2, layer3 }, readme, cityName }
 */
function streamZip(outputStream, { svgLayers, readme, cityName }) {
  return new Promise((resolve, reject) => {
    const archive = archiver('zip', {
      zlib: { level: 9 },
    });

    archive.on('error', (err) => {
      reject(err);
    });

    archive.on('end', () => {
      resolve();
    });

    // Pipe archive to output stream
    archive.pipe(outputStream);

    // Add SVG files
    const prefix = cityName || 'LaserMap';
    archive.append(svgLayers.layer1, { name: `${prefix}/Layer1_MajorRoads.svg` });
    archive.append(svgLayers.layer2, { name: `${prefix}/Layer2_MinorRoads.svg` });
    archive.append(svgLayers.layer3, { name: `${prefix}/Layer3_Base.svg` });

    // Add README
    archive.append(readme, { name: `${prefix}/README.txt` });

    // Finalize
    archive.finalize();
  });
}

module.exports = {
  generateReadme,
  streamZip,
};
